### PR TITLE
Remove redundant closure

### LINKED ISSUE #2345: CI jobs failing with "error: redundant closure"
**Platform I'm building on:**

All

**What I expected to happen:**

No error.

**What actually happened:**

Starting today, I just started noticing all builds failing on a couple of new PR's with the message:

```
error: redundant closure
   --> testsys/src/aws_resources.rs:470:19
    |
470 |         .flat_map(|image| identity(image))
    |                   ^^^^^^^^^^^^^^^^^^^^^^^ help: replace the closure with the function itself: `identity`
    |
    = note: `-D clippy::redundant-closure` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure

error: could not compile `testsys` due to previous error
```

The error looks legitimate, though it's surprising it just started happening since this code has been in place for almost a month.

**How to reproduce the problem:**

Build.

### PR DESCRIPTION
**Pull request by stmcginnis**
**Issue number:**

Closes #2345 

**Description of changes:**

Clippy warnings about a redundant closure. The closure just makes a call
to a function that would take the passed argument anyway, so we should
remove the closure and just provide the function directly.

**Testing done:**

Built with changes and verified rust was happy.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by zmrow — APPROVED** [review]
:feather:

**Review by etungsten — DISMISSED** [review]

File: tools/testsys/src/aws_resources.rs [hunk 1]
```diff
@@ -465,10 +465,7 @@ where
         .send()
         .await?
         .images;
-    let images: Vec<&Image> = describe_images
-        .iter()
-        .flat_map(|image| identity(image))
-        .collect();
+    let images: Vec<&Image> = describe_images.iter().flat_map(identity).collect();
```
Comment (etungsten) [inline tools/testsys/src/aws_resources.rs]: From clippy in actions workflow:
```
error: use of `flat_map` with an identity function
   --> testsys/src/aws_resources.rs:468:54
    |
468 |     let images: Vec<&Image> = describe_images.iter().flat_map(identity).collect();
    |                                                      ^^^^^^^^^^^^^^^^^^ help: try: `flatten()`
    |
    = note: `-D clippy::flat-map-identity` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#flat_map_identity
```

Comment (stmcginnis) [reply tools/testsys/src/aws_resources.rs]: I had to do some more reading and testing, but think it's good now. Still a little new on rust, so if someone can confirm everything looks good now, I'll hold off on merging to give folks a chance to take a look.

**Review by ecpullen — APPROVED** [review]

**Review by etungsten — APPROVED** [review]
