### PR TITLE
pubsys: fix bug preventing multiple ssm promotions

### LINKED ISSUE #3103: pubsys: Using `promote-ssm` in a tiered promotion structure causes pubsys to panic
**What I expected to happen:**
When calling `pubsys promote-ssm` using `--ssm-parameter-output` multiple times to perform a tiered rollout of SSM parameter deployments, then SSM parameters should be successfully promoted along those tiers.

**What actually happened:**
```
thread 'main' panicked at 'no entry found for key', pubsys/src/aws/promote_ssm/mod.rs:291:49
```

A few problems exist here:
* The `combine_parameters` file makes an assumption that all existing parameters in the file are being mapped to a target during the promotion, but in cases of tiered promotions, that isn't true.
* We use an Index operation on a HashMap which panics if the content is not accessible.

**How to reproduce the problem:**
* Use `pubsys ssm --ssm-parameter-output $PATH` to create a set of SSM parameters
* Use `pubsys promote-ssm --ssm-parameter-output $PATH` to promote those to a new set of SSM parameters
* Use `pubsys promote-ssm --ssm-parameter-output $PATH` to once again promote those to a final set of parameters.

**Existing Workaround:**
You can work around this issue for now by refraining from using `--ssm-parameter-output` with pubsys. You may need to modify `Makefile.toml` if you are interfacing with pubsys via cargo-make.

### PR DESCRIPTION
**Pull request by cbgbt**
**Issue number:**

Closes #3103

**Description of changes:**
The goal of this feature is to keep a file of all published SSM parameters for the current Bottlerocket build.

During promotions, we parse the existing SSM file then add any newly created SSM parameter.

Prior to this change, the code which combines prior state with the newly-created parameters falsely assumed that all constructed promoted parameters would have a 1:1 mapping with a parameter that already exists in the file. This fails in some cases, e.g. when performing tiered promotions where the first tier is largely irrelevant when performing a promotion from the second to the third tier.

The change modifies the code to simply concatenate the existing data with any newly-created parameter, overwriting if the key exists.

**Testing done:**
* [x] unit tests pass
* [x] manual testing of a tiered promotion

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

File: tools/pubsys/src/aws/promote_ssm/mod.rs [hunk 1]
```diff
@@ -388,31 +382,30 @@ type Result<T> = std::result::Result<T, error::Error>;
...
-                )]),
+                SsmKey::new(Region::new("us-west-2"), "test2-parameter-name".to_string()),
+                "test2-parameter-value".to_string(),
+            ),
+            (
+                SsmKey::new(Region::new("us-east-1"), "test3-parameter-name".to_string()),
+                "test3-parameter-value".to_string(),
+            ),
+            (
+                SsmKey::new(
```
Comment (zmrow) [inline tools/pubsys/src/aws/promote_ssm/mod.rs:404]: This is just an additional key yeah?  I'm not missing more context there?

**Review by zmrow — APPROVED** [review]
Looks good; great simplification! :fireworks: 

Provided the manual testing goes well, I'm happy.

File: tools/pubsys/src/aws/promote_ssm/mod.rs (hunk 1 above)
Comment (cbgbt) [reply tools/pubsys/src/aws/promote_ssm/mod.rs:404]: Correct! The idea was that this key isn't involved in the promotion.

This test would fail on the previous commit.

**Review by yeazelm — APPROVED** [review]

**Review by stmcginnis — APPROVED** [review]

**Review by stmcginnis — APPROVED** [review]
Just some lint issues to resolve.

**Comment by cbgbt** [comment]
^ fixes clippy warnings.

**Review by etungsten — APPROVED** [review]
