### PR TITLE
static-pods: write manifest to tempfile before persisting it

### LINKED ISSUE #1396: concurrent creation of static pods is error prone
**Image I'm using:**
aws-k8s-1.19

**What I expected to happen:**
When setting static pods in a loop, I expected them all to come up independently and not interfere with other pods.

**What actually happened:**
> Mar 16 01:32:57 ip-10-0-167-200.us-west-2.compute.internal kubelet[3919]: E0316 01:32:57.651483    3919 file.go:108] Unable to process watch event: can't process config file "/etc/kubernetes/static-pods/kube-apiserver": /etc/kubernetes/static-pods/kube-apiserver: couldn't parse as pod(Object 'Kind' is missing in 'null'), please check config file
>
> Mar 16 01:32:57 ip-10-0-167-200.us-west-2.compute.internal kubelet[3919]: E0316 01:32:57.654182    3919 file.go:108] Unable to process watch event: can't process config file "/etc/kubernetes/static-pods/etcd": /etc/kubernetes/static-pods/etcd: couldn't parse as pod(Object 'Kind' is missing in 'null'), please check config file

**How to reproduce the problem:**
Set static pods in a loop like this.
```
for pod in kube-apiserver kube-scheduler kube-controller-manager ; do
  apiclient set \
    "kubernetes.static-pods.${pod}.manifest"="$(base64 -w 0 manifests/$pod.yaml)" \
    "kubernetes.static-pods.${pod}.enabled"=true
done
```

### PR DESCRIPTION
**Pull request by etungsten**
**Issue number:**
Fixes https://github.com/bottlerocket-os/bottlerocket/issues/1396

**Description of changes:**
```
Author: Erikson Tung <etung@amazon.com>
Date:   Tue Mar 23 16:52:49 2021 -0700

    static-pods: write manifest to tempfile before persisting it
    
    When writing static pod manifest, create them as temporary files and
    finish writing to them before persisting them in the destination file
    path.

```

**Testing done:**
Built aws-k8s-1.19 image and launched 4 instances

For each instance I was able to set 3 static pods repeatedly like so:
```
[ec2-user@ip ~]$ for pod in a b c ; do
apiclient set \
   "kubernetes.static-pods.${pod}.manifest"="$(base64 -w 0 manifests/$pod.yaml)" \
   "kubernetes.static-pods.${pod}.enabled"=true
done

```

Then `sudo sheltie`d to check kubelet logs. I no longer see any error logs pertaining to empty config files. All static pods gets created successfully and runs on the node. I repeated the for loop a few more times to make sure.

<details>

Note that the three static pods I created uses a generic manifest for nginx pods, that's why the image is `docker.io/library/nginx:1.14.2`

```
bash-5.0# cat /etc/kubernetes/static-pods/*  
apiVersion: v1
kind: Pod
metadata:
   name: a
spec:
   containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
           - containerPort: 80
apiVersion: v1
kind: Pod
metadata:
   name: b
spec:
   containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
           - containerPort: 82
apiVersion: v1
kind: Pod
metadata:
   name: c
spec:
   containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
           - containerPort: 81
```

```
bash-5.0# ctr -a /run/dockershim.sock -n k8s.io containers ls
CONTAINER                                                           IMAGE                                                                                                                                      
18a40cad51210af34b8f6d98920980b9eb5ca487c7b69d8c7c762deaf2b9faa8    docker.io/library/nginx:1.14.2                                                                                                         
280cdd55cc9fdd60fd3b145880480d65953427f0d7870a75c909ee51604e8530    docker.io/library/nginx:1.14.2                                                                                                         
f1f31d9d25523bfb110fd1f050fa7feaa9689762a119831f11b5306e43f266d6    docker.io/library/nginx:1.14.2            
...
```

</details>

I also tried launching instances with static pods specified in the userdata, those pods also get created successfully.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by etungsten** [comment]
One thing to note, kubelet is emitting error logs for static pods created *after* the node becomes `Ready`:
```
E0324 00:46:36.333789    3307 kubelet.go:1690] Failed creating a mirror pod for "c-ip-192-168-23-17.us-west-2.compute.internal_default(18df3f29b7ba9816f25786dcb540583a)": admission webhook "mpod.vpc.k8s.aws" denied the request: Webhood encountered error to Get or List object from k8s cache.
E0324 00:46:43.330796    3307 kubelet.go:1690] Failed creating a mirror pod for "a-ip-192-168-23-17.us-west-2.compute.internal_default(7a59cd048f86ed600cb60ce139d6c6a7)": admission webhook "mpod.vpc.k8s.aws" denied the request: Webhood encountered error to Get or List object from k8s cache.
E0324 00:47:13.324773    3307 kubelet.go:1690] Failed creating a mirror pod for "b-ip-192-168-23-17.us-west-2.compute.internal_default(c642be10819ecae0d36bdd4f6efe8dbf)": admission webhook "mpod.vpc.k8s.aws" denied the request: Webhood encountered error to Get or List object from k8s cache.

``` 

This has no impact on the static-pods themselves. They are just not visible via the `kubectl` client. The pods are actually running fine on the node (as shown in the containerd tasks list). `kubectl get events` also shows the static pods starting up:
```
LAST SEEN   TYPE      REASON                   OBJECT                                                                   MESSAGE
20m         Normal    Pulling                  pod/a-ip-192-168-3-162.us-west-2.compute.internal                        Pulling image "nginx:1.14.1"
19m         Normal    Pulled                   pod/a-ip-192-168-3-162.us-west-2.compute.internal                        Successfully pulled image "nginx:1.14.1"
19m         Normal    Created                  pod/a-ip-192-168-3-162.us-west-2.compute.internal                        Created container nginx
19m         Normal    Started                  pod/a-ip-192-168-3-162.us-west-2.compute.internal                        Started container nginx
20m         Normal    Pulling                  pod/b-ip-192-168-3-162.us-west-2.compute.internal                        Pulling image "nginx:1.14.1"
19m         Normal    Pulled                   pod/b-ip-192-168-3-162.us-west-2.compute.internal                        Successfully pulled image "nginx:1.14.1"
19m         Normal    Created                  pod/b-ip-192-168-3-162.us-west-2.compute.internal                        Created container nginx
19m         Normal    Started                  pod/b-ip-192-168-3-162.us-west-2.compute.internal                        Started container nginx
20m         Normal    Pulling                  pod/c-ip-192-168-3-162.us-west-2.compute.internal                        Pulling image "nginx:1.14.1"
19m         Normal    Pulled                   pod/c-ip-192-168-3-162.us-west-2.compute.internal                        Successfully pulled image "nginx:1.14.1"
19m         Normal    Created                  pod/c-ip-192-168-3-162.us-west-2.compute.internal                        Created container nginx
19m         Normal    Started                  pod/c-ip-192-168-3-162.us-west-2.compute.internal                        Started container nginx
```

This happens for images before this fix as well. But I do not remember seeing this error when I was testing the static-pods feature for the 1.0.6 release.

The weird thing is, static-pods created via user-data are fine; kubelet is able to create a mirror pod for them without problem. This and the fact that the logs say `"mpod.vpc.k8s.aws" denied the request` makes me think a recent version of the VPC CNI plugin is causing this. I'm not entirely sure why though.

File: sources/api/static-pods/src/static_pods.rs [hunk 1]
```diff
@@ -54,13 +55,27 @@ where
     S2: AsRef<[u8]>,
 {
     let name = name.as_ref();
-
```
Comment (tjkirch) [inline sources/api/static-pods/src/static_pods.rs:57]: nit: this newline serves a (minor) purpose; the `as_ref` call is more like parameter management than anything to do with the function body (used when we have an AsRef parameter only used in target form, and used many times) so we typically separate it with a newline to represent that anything following is "real" work as part of the function.

File: sources/api/static-pods/src/static_pods.rs [hunk 2]
```diff
@@ -54,13 +55,27 @@ where
...
     fs::create_dir_all(&dir).context(error::Mkdir { dir: &dir })?;
-    let path = dir.join(name);
-    // Create the file if it does not exist, completely replace its contents
-    // if it does (constitutes an update).
-    fs::write(path, manifest).context(error::ManifestWrite { name })?;
+
+    // Create the pod manifest file as a temporary file first and finish writing to it
+    // before swapping any files out
+    let mut temp_manifest_file =
+        NamedTempFile::new_in(STATIC_POD_DIR).context(error::CreateTempfile)?;
```
Comment (tjkirch) [inline sources/api/static-pods/src/static_pods.rs]:
```suggestion
        NamedTempFile::new_in(&dir).context(error::CreateTempfile)?;
```
I think it doesn't have to recreate the Path this way.  Also makes it clearer to the reader that it's not a different place.

File: sources/api/static-pods/src/static_pods.rs [hunk 3]
```diff
@@ -54,13 +55,27 @@ where
...
+    temp_manifest_file
+        .write(manifest.as_ref())
+        .context(error::ManifestWrite { name })?;
+
+    let tempfile_path = temp_manifest_file.into_temp_path();
```
Comment (tjkirch) [inline sources/api/static-pods/src/static_pods.rs]: Do we have to go through the `TempPath` rather than calling `temp_manifest_file.persist(bla)` directly?

**Review by tjkirch — APPROVED** [review]

**Comment by etungsten** [comment]
Push above addresses @tjkirch 's comments. Tested the changes, results are the same as described in the PR testing description.

File: sources/api/static-pods/src/static_pods.rs [hunk 4]
```diff
@@ -54,13 +55,27 @@ where
...
-    // Create the file if it does not exist, completely replace its contents
-    // if it does (constitutes an update).
-    fs::write(path, manifest).context(error::ManifestWrite { name })?;
+
+    // Create the pod manifest file as a temporary file first and finish writing to it
+    // before swapping any files out
+    let mut temp_manifest_file = NamedTempFile::new_in(dir).context(error::CreateTempfile)?;
+    temp_manifest_file
+        .write(manifest)
+        .context(error::ManifestWrite { name })?;
```
Comment (bcressey) [inline sources/api/static-pods/src/static_pods.rs]: This fixes the case where a manifest exists that kubelet is watching, but it seems like it has the same potential problem for a newly created manifest: kubelet could try to load it before we've written any content, or before we've finished writing it.

Comment (tjkirch) [reply sources/api/static-pods/src/static_pods.rs]: It loads any file in that directory regardless of name?  I was assuming it'd look for at least _some_ kind of pattern.  If that's the case, we could put the temp file in a parent directory, or a new temp directory we create next to the target directory..?

**Comment by etungsten** [comment]
Push above addresses @bcressey 's comment.
Now static pod manifests are first created and written to in an adjacent tmp directory before getting persisted in the target file path.

Tested with the same steps in the PR description, and things work as expected.

File: sources/api/static-pods/src/static_pods.rs [hunk 5]
```diff
@@ -11,21 +11,23 @@ It queries for all existing static pod settings, then configures the system as f
...
 use std::str::FromStr;
-
-use model::modeled_types::Identifier;
+use tempfile::NamedTempFile;
 
 // FIXME Get from configuration in the future
 const DEFAULT_API_SOCKET: &str = "/run/api.sock";
 
 const STATIC_POD_DIR: &str = "/etc/kubernetes/static-pods";
+const STATIC_POD_TEMP_DIR: &str = "/etc/kubernetes/tmp-static-pods/";
```
Comment (tjkirch) [inline sources/api/static-pods/src/static_pods.rs]: We should be able to use a `TempDir` rather than keeping around this thing.

**Comment by etungsten** [comment]
Push above addresses https://github.com/bottlerocket-os/bottlerocket/pull/1409#discussion_r600847331

Tested things and they work as described in the PR description still. The temporary directory gets cleaned-up correctly when it goes out of scope.

**Review by webern — APPROVED** [review]

**Review by tjkirch — APPROVED** [review]

**Review by bcressey — APPROVED** [review]
