### PR TITLE
signpost: `cancel-upgrade` behavior fix

### LINKED ISSUE #949: signpost: cancel-upgrade behavior misleading
**Image I'm using:**
aws-k8s-1.15 v0.3.4 

**What I expected to happen:**

According to the usage information for the signpost commands:
```
    mark-inactive-valid     Marks the inactive partition as having a valid image
    upgrade-to-inactive     Sets the inactive partitions as new upgrade partitions if marked valid
    cancel-upgrade          Reverse upgrade-to-inactive
```

If I call `mark-inactive-valid` and `upgrade-to-inactive` to set the inactive partition as the "next-to-boot" and then call `cancel-upgrade` to revert `upgrade-to-inactive`, I should be able to call `upgrade_to_inactive` successfully afterwards to restore the inactive partition as `next-to-boot` without having to call `mark-inactive-valid` again.

**What actually happened:**
`cancel-upgrade` wipes all the priority bits, including number of `tries_left` (validity), so a subsequent `upgrade-to-inactive` would fail because the inactive partition is no longer marked as valid.

**How to reproduce the problem:**
Initial partition table
```
bash-5.0# signpost status        
OS disk: /dev/nvme0n1
Set A:   boot=/dev/nvme0n1p2 root=/dev/nvme0n1p3 hash=/dev/nvme0n1p4 priority=2 tries_left=0 successful=true
Set B:   boot=/dev/nvme0n1p6 root=/dev/nvme0n1p7 hash=/dev/nvme0n1p8 priority=0 tries_left=0 successful=false
Active:  Set A
Next:    Set A
```

Call `mark-inactive-valid` to set number of tries left for the inactive partition to 1 (thereby marking it valid for boot)
```
bash-5.0# signpost mark-inactive-valid
bash-5.0# signpost status             
OS disk: /dev/nvme0n1
Set A:   boot=/dev/nvme0n1p2 root=/dev/nvme0n1p3 hash=/dev/nvme0n1p4 priority=2 tries_left=0 successful=true
Set B:   boot=/dev/nvme0n1p6 root=/dev/nvme0n1p7 hash=/dev/nvme0n1p8 priority=0 tries_left=1 successful=false
Active:  Set A
Next:    Set A
```

Call `upgrade-to-inactive` to set inactive partition as next to boot.
```
bash-5.0# signpost upgrade-to-inactive
bash-5.0# signpost status             
OS disk: /dev/nvme0n1
Set A:   boot=/dev/nvme0n1p2 root=/dev/nvme0n1p3 hash=/dev/nvme0n1p4 priority=1 tries_left=0 successful=true
Set B:   boot=/dev/nvme0n1p6 root=/dev/nvme0n1p7 hash=/dev/nvme0n1p8 priority=2 tries_left=1 successful=false
Active:  Set A
Next:    Set B
```

Call `cancel-upgrade` to rollback `upgrade-to-inactive`, but it rolls back both `upgrade-to-inactive` AND `mark-inactive-valid` (tries_left is no longer set to 1) so subsequent `upgrade-to-inactive` calls no longer work
```
bash-5.0# signpost cancel-upgrade     
bash-5.0# signpost status        
OS disk: /dev/nvme0n1
Set A:   boot=/dev/nvme0n1p2 root=/dev/nvme0n1p3 hash=/dev/nvme0n1p4 priority=2 tries_left=0 successful=true
Set B:   boot=/dev/nvme0n1p6 root=/dev/nvme0n1p7 hash=/dev/nvme0n1p8 priority=0 tries_left=0 successful=false
Active:  Set A
Next:    Set A
bash-5.0# signpost upgrade-to-inactive
Inactive partition /dev/nvme0n1 has not been marked valid for upgrade
```

### PR DESCRIPTION
**Pull request by etungsten**
**Issue number:** Fixes https://github.com/bottlerocket-os/bottlerocket/issues/949

**Description of changes:** 
```
Author: Erikson Tung <etung@amazon.com>
Date:   Fri Jun 19 11:55:10 2020 -0700

    signpost: `cancel-upgrade` behavior update
    
    Changes `cancel-upgrade` so that it only reverts actions done by
    `upgrade-to-inactive` as the usage information implies.
    `cancel-upgrade` now preserves the number of tries left on the
    inactive partition instead of just wiping all bits

```

**Testing done:**
Initial status:
```
bash-5.0# signpost status
OS disk: /dev/nvme0n1
Set A:   boot=/dev/nvme0n1p2 root=/dev/nvme0n1p3 hash=/dev/nvme0n1p4 priority=1 tries_left=0 successful=true
Set B:   boot=/dev/nvme0n1p6 root=/dev/nvme0n1p7 hash=/dev/nvme0n1p8 priority=0 tries_left=0 successful=false
Active:  Set A
Next:    Set A
```

Mark inactive partition as valid, see tries_left set to 1
```
bash-5.0# signpost mark-inactive-valid
bash-5.0# signpost status             
OS disk: /dev/nvme0n1
Set A:   boot=/dev/nvme0n1p2 root=/dev/nvme0n1p3 hash=/dev/nvme0n1p4 priority=1 tries_left=0 successful=true
Set B:   boot=/dev/nvme0n1p6 root=/dev/nvme0n1p7 hash=/dev/nvme0n1p8 priority=0 tries_left=1 successful=false
Active:  Set A
Next:    Set A
```

Make the inactive as next to boot, see priority bumped to 2
```
bash-5.0# signpost upgrade-to-inactive
bash-5.0# signpost status             
OS disk: /dev/nvme0n1
Set A:   boot=/dev/nvme0n1p2 root=/dev/nvme0n1p3 hash=/dev/nvme0n1p4 priority=1 tries_left=0 successful=true
Set B:   boot=/dev/nvme0n1p6 root=/dev/nvme0n1p7 hash=/dev/nvme0n1p8 priority=2 tries_left=1 successful=false
Active:  Set A
Next:    Set B
```

`cancel-upgrade` then properly rolls back `upgrade-to-inactive` by setting the priority back to 0 while keeping `tries_left` at 1
```
bash-5.0# signpost cancel-upgrade                                                                                                                                             
bash-5.0# signpost status        
OS disk: /dev/nvme0n1
Set A:   boot=/dev/nvme0n1p2 root=/dev/nvme0n1p3 hash=/dev/nvme0n1p4 priority=2 tries_left=0 successful=true
Set B:   boot=/dev/nvme0n1p6 root=/dev/nvme0n1p7 hash=/dev/nvme0n1p8 priority=0 tries_left=1 successful=false
Active:  Set A
Next:    Set A
```

Subsequent `upgrade-to-inactive` call is successful because the inactive partition is still marked valid (`tries_left` > 0)
```
bash-5.0# signpost upgrade-to-inactive
bash-5.0# signpost status             
OS disk: /dev/nvme0n1
Set A:   boot=/dev/nvme0n1p2 root=/dev/nvme0n1p3 hash=/dev/nvme0n1p4 priority=1 tries_left=0 successful=true
Set B:   boot=/dev/nvme0n1p6 root=/dev/nvme0n1p7 hash=/dev/nvme0n1p8 priority=2 tries_left=1 successful=false
Active:  Set A
Next:    Set B
```

`cancel-upgrade` then restores active partition as next to boot.
Another `clear-inactive` call then wipes the inactive partition priority bits.
```
bash-5.0# signpost cancel-upgrade     
bash-5.0# signpost status             
OS disk: /dev/nvme0n1
Set A:   boot=/dev/nvme0n1p2 root=/dev/nvme0n1p3 hash=/dev/nvme0n1p4 priority=2 tries_left=0 successful=true
Set B:   boot=/dev/nvme0n1p6 root=/dev/nvme0n1p7 hash=/dev/nvme0n1p8 priority=0 tries_left=1 successful=false
Active:  Set A
Next:    Set A
bash-5.0# signpost clear-inactive
bash-5.0# signpost status        
OS disk: /dev/nvme0n1
Set A:   boot=/dev/nvme0n1p2 root=/dev/nvme0n1p3 hash=/dev/nvme0n1p4 priority=2 tries_left=0 successful=true
Set B:   boot=/dev/nvme0n1p6 root=/dev/nvme0n1p7 hash=/dev/nvme0n1p8 priority=0 tries_left=0 successful=false
Active:  Set A
Next:    Set A
bash-5.0# 
```

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

File: sources/updater/signpost/src/state.rs [hunk 1]
```diff
@@ -243,10 +243,14 @@ impl State {
...
     ///
-    /// * Clears all bits of the inactive partition.
+    /// * Sets the inactive partition's priority to 0
+    /// * Sets the inactive partition as not successfully booted.
     /// * Restores the active partition's priority to 2
     pub fn cancel_upgrade(&mut self) {
-        self.clear_inactive();
+        let mut inactive_flags = self.gptprio(self.inactive());
+        inactive_flags.set_priority(0);
+        inactive_flags.set_successful(false);
```
Comment (tjkirch) [inline sources/updater/signpost/src/state.rs]: Is setting successful=false necessary?  It's seems unrelated to canceling an upgrade.  Maybe the other partition has been booted successfully..?

**Comment by etungsten** [comment]
Push above addresses @tjkirch 's comment.

**Review by tjkirch — APPROVED** [review]
Would like to make sure @iliana approves.

**Review by iliana — APPROVED** [review]
