### PR TITLE
Updog: use compile time specific json payloads in unit tests

### LINKED ISSUE #2366: Updog unit tests broken on `aarch` - have hard coded `x86_64` values
### Platform I'm building on:

OS: Fedora 34 (Cloud Edition) aarch64
Host: c6g.8xlarge
Kernel: 5.11.12-300.fc34.aarch64

### What I expected to happen:

Running `cargo make unit-tests` to succeed.

### What actually happened:

`updog` tests fail with the following error

```
     Running unittests src/main.rs (sources/target/debug/deps/updog-cdf0c72c09f942b1)

running 10 tests
test tests::check_update_waves ... ok
test tests::serialize_metadata ... ok
test tests::test_serde_reader ... ok
test tests::older_versions ... FAILED
test tests::test_versions ... ok
test tests::force_update_version ... FAILED
test tests::test_multiple ... FAILED
test tests::test_manifest_json ... ok
test tests::bad_bound ... ok
test tests::duplicate_bound ... ok

failures:

---- tests::older_versions stdout ----
thread 'tests::older_versions' panicked at 'Updog ignored max version', updater/updog/src/main.rs:729:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::force_update_version stdout ----
thread 'tests::force_update_version' panicked at 'Updog failed to find an update', updater/updog/src/main.rs:810:9

---- tests::test_multiple stdout ----
thread 'tests::test_multiple' panicked at 'Incorrect version: 1.16.0, should be 1.15.0', updater/updog/src/main.rs:770:13


failures:
    tests::force_update_version
    tests::older_versions
    tests::test_multiple

test result: FAILED. 7 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.75s

error: test failed, to rerun pass '-p updog --bin updog'
[cargo-make] ERROR - Error while executing command, exit code: 101
[cargo-make] WARN - Build Failed.
```

Notice that `x86_64` is hard coded in a few spots, primiarily the stub JSON data:

https://github.com/bottlerocket-os/bottlerocket/blob/ad3fa442b8e0b4c533d930b8b524cdae5c6d9abd/sources/updater/updog/tests/data/example_3.json#L5

How to reproduce the problem:

Run unit tests for bottlerocket on a aarch dev box 

**Next steps**: Make the hardcoded data more dynamic and able to be run on either x86 or aarch

### PR DESCRIPTION
**Pull request by jpmcb**
**Issue number:**

Closes #2366

**Description of changes:**

```
Modifies the updog unit tests to use architecture specific json stub
files when those tests make assertions based on the host architecture.

This patch fixes unit tests not working on aarch machines due to hard
coded "x86_64" string literals.

Signed-off-by: John McBride <jpmmcb@amazon.com>
```

Adds a few files for `aarch64` based machines and modifies the names of previous files to be have the new naming convention.

**Testing done:**

Now able to fully run `cargo make unit-tests` with no errors

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

File: sources/updater/updog/src/main.rs [hunk 1]
```diff
@@ -700,8 +700,9 @@ mod tests {
 
     #[test]
     fn older_versions() {
-        // A manifest with two updates, both less than 0.1.3
-        let path = "tests/data/example_3.json";
+        // A manifest with two updates, both less than 0.1.3.
+        // Use a architecture specific JSON payload, otherwise Updog will ignore the update
```
Comment (etungsten) [inline sources/updater/updog/src/main.rs]: nit: we use lowercase when referencing our first party binaries.
```suggestion
        // Use a architecture specific JSON payload, otherwise updog will ignore the update
```

This applies to the commit message as well.

**Review by etungsten — APPROVED** [review]
:dog2:

File: sources/updater/updog/src/main.rs (hunk 1 above)
Comment (jpmcb) [reply sources/updater/updog/src/main.rs]: Gotcha! Good to know 👍🏼

**Comment by jpmcb** [comment]
Force pushed to update `%s/Updog/updog/` in comment and commit message

**Review by zmrow — APPROVED** [review]
:singer:
