### PR TITLE
updog: ignore termination signals right before initiating reboot

### LINKED ISSUE #864: Updater exits non-zero when passed flag to reboot
**Image I'm using:**

Updating `aws-k8s-v0.3.0` to `aws-k8s-v0.3.1`.

**What I expected to happen:**

I expected that the [Bottlerocket update operator](https://github.com/bottlerocket-os/bottlerocket-update-operator) would be able to call the host's updater executable - `updog` - to apply, switch to, and reboot to an update and observe a successful exit status. The update operator expects that the updater will exit with a zero status whenever it has successfully applied or performed the requested action (and a non-zero when an error is encountered).

**What actually happened:**

Sometimes\* when the update operator calls `updog` to apply the update and reboot, the executed `updog` gets sent a `SIGTERM` by the `init` system as it begins to kill process trees. Because `updog` does not handle the `SIGTERM` it exits non-zero and the update operator reports that its updater process (`updog`) failed to flip and reboot to the updated partition. This error causes the update operator agent and controller to leave a node cordoned off from the cluster.

This was observed and reported in https://github.com/bottlerocket-os/bottlerocket-update-operator/issues/28

\*: I see this behavior approximately 20% of the time in a cluster of 16.

**How to reproduce the problem:**

Use a cluster that upgrades from `v0.3.0` to `v0.3.1` and the [Bottlerocket update operator deployment](https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/7fcaf306d983df8542bb31bcad68a9142cde82cf/update-operator.yaml). I used the following `ClusterConfig` for `eksctl` and used a image built from the `v0.3.0` tag to upgrade from.

``` yaml
# v0.3.0 repro cluster
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: brupop
  region: us-west-2
  version: '1.15'

nodeGroups:
  - name: launched-as--0-3-0
    instanceType: m5.large
    desiredCapacity: 16
    amiFamily: Bottlerocket
    # Private AMI built from v0.3.0 in us-west-2
    ami: ami-ffffffffffffffff
    labels:
      "bottlerocket.aws/platform-version": "1.0.0"
    ssh:
      allow: true
      publicKeyName: my-key
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
```

I used the ASG that `eksctl` created to make passes at reproducing this issue:

``` shell
# Update to scale in and out for getting dead nodes:
aws autoscaling update-auto-scaling-group --auto-scaling-group-name "$ASG_NAME" --min-size 0

# Then scale in and out as needed to observe:
#
# Scale in:
aws autoscaling set-desired-capacity --auto-scaling-group-name "$ASG_NAME" --desired-capacity 0
# Scale out:
aws autoscaling set-desired-capacity --auto-scaling-group-name "$ASG_NAME" --desired-capacity 16
```

### PR DESCRIPTION
**Pull request by etungsten**
**Issue number:**
Fixes https://github.com/bottlerocket-os/bottlerocket/issues/864 and partially addresses https://github.com/bottlerocket-os/bottlerocket-update-operator/issues/28

**Description of changes:**
Termination signals are ignored right before `shutdown -r` invocation.
This change allows `updog` to exit normally (with exit code 0, as to indicate a successful update
operation) after initiating reboot. 

**Testing done:**

1. Built Bottlerocket image with release version set to 0.3.0.
2. Created an ASG with 18 instances of said image and have all instances join my cluster
3. Installed [bottlerocket-update-operator](https://github.com/bottlerocket-os/bottlerocket-update-operator) on my cluster.
4. Observed all 18 nodes automatically upgraded from my dirty v0.3.0 to the v0.3.1 image from the TUF repository successfully one by one.
5. All nodes uncordoned successfully, and can run pods fine. 

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

File: sources/updater/updog/src/main.rs [hunk 1]
```diff
@@ -437,6 +439,23 @@ fn output<T: Serialize>(json: bool, object: T, string: &str) -> Result<()> {
     Ok(())
 }
 
+fn initiate_reboot() -> Result<()> {
+    // Set up signal handler for termination signals
+    let signals = Signals::new(&[SIGINT, SIGTERM, SIGQUIT]).context(error::Signal)?;
```
Comment (tjkirch) [inline sources/updater/updog/src/main.rs]: I think we should scope this to the signal(s) we actually get from the shutdown process.  That's just TERM, right?  (brupop isn't sending anything special?)  INT and QUIT are typically signals from humans, and if a human (or their code) is calling updog and they kill it because reboot hung or whatever, we don't want it to look successful.

File: sources/updater/updog/src/main.rs [hunk 2]
```diff
@@ -437,6 +439,23 @@ fn output<T: Serialize>(json: bool, object: T, string: &str) -> Result<()> {
...
+        for _sig in signals.forever() {
+            // Ignore termination signals in case updog gets terminated
+            // before getting to exit normally by itself after invoking
+            // `shutdown -r` to complete the update.
+        }
+    });
+    process::Command::new("shutdown")
+        .arg("-r")
+        .status()
+        .context(error::RebootFailure)?;
```
Comment (tjkirch) [inline sources/updater/updog/src/main.rs]: If we fail to call the shutdown binary, technically we should kill the signal thread.  I think we can get away without it because we know (currently) the code just prints a backtrace in that case, but it'd be nice to prevent future confusion.

**Comment by etungsten** [comment]
Push above addresses @tjkirch 's comments.

- Limit signal handling to just SIGTERM.
- Kill signal handling thread if shutdown invocation fails for whatever reason. See [signal_hook::iterator::Signals::close](https://docs.rs/signal-hook/0.1.13/signal_hook/iterator/struct.Signals.html#method.close)

**Review by sam-aws — APPROVED** [review]

**Review by tjkirch — APPROVED** [review]
LGTM, but would you please confirm the testing is still OK with the reduced signal set?

**Comment by etungsten** [comment]
> LGTM, but would you please confirm the testing is still OK with the reduced signal set?

I tested the new changes with the steps in the PR description and everything still works as expected.
