### PR TITLE
Mount static kmod as /sbin/modprobe

### LINKED ISSUE #3968: Changes to kernel module compression can break certain workflows
**Image I'm using:**
All Bottlerocket OS 1.20.0 variants

**What I expected to happen:**
Updating to Bottlerocket v1.20.0 should not have broken any existing container workflows.

**What actually happened:**
Launching Bottlerocket v1.20.0 can result in unexpected errors like:
```
level=warning msg="iptables modules could not be initialized. It probably means that iptables is not available on this system" error="could not load module iptable_raw: exit status
```
or
```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process:
```

**Root Cause:**
Following [changes](https://github.com/bottlerocket-os/bottlerocket/pull/3861) in Bottlerocket v1.20.0 we dropped support for `xz` compressed modules in favour of `gz` compression. We're seeing failures to launch certain containers which require kernel modules and have `modprobe` built without `libz (gzip)` support. 

Known Affected systems:
- Cilium

**Workaround:**
A workaround would be to use user data on new launches or `apiclient` in running hosts to setup `kernel.modules.<name>.autoload` to load the required modules as described [here](https://bottlerocket.dev/en/os/1.19.x/api/settings/kernel/#modules_autoload).

In the case of Cilium the commands would like the following when using the apiclient:
```
apiclient set \
  settings.kernel.modules.ip_tables.allowed=true \
  settings.kernel.modules.ip_tables.autoload=true \
  settings.kernel.modules.iptable_nat.allowed=true \
  settings.kernel.modules.iptable_nat.autoload=true \
  settings.kernel.modules.iptable_mangle.allowed=true \
  settings.kernel.modules.iptable_mangle.autoload=true \
  settings.kernel.modules.iptable_raw.allowed=true \
  settings.kernel.modules.iptable_raw.autoload=true \
  settings.kernel.modules.iptable_filter.allowed=true \
  settings.kernel.modules.iptable_filter.autoload=true \
  settings.kernel.modules.ip6table_mangle.allowed=true \
  settings.kernel.modules.ip6table_mangle.autoload=true \
  settings.kernel.modules.ip6table_raw.allowed=true \
  settings.kernel.modules.ip6table_raw.autoload=true \
  settings.kernel.modules.ip6table_filter.allowed=true \
  settings.kernel.modules.ip6table_filter.autoload=true
```
OR via `user-data.toml`:
```
[settings.kernel.modules.ip_tables]
allowed = true
autoload = true

[settings.kernel.modules.iptable_nat]
allowed = true
autoload = true

[settings.kernel.modules.iptable_mangle]
allowed = true
autoload = true

[settings.kernel.modules.iptable_raw]
allowed = true
autoload = true

[settings.kernel.modules.iptable_filter]
allowed = true
autoload = true

[settings.kernel.modules.ip6table_mangle]
allowed = true
autoload = true

[settings.kernel.modules.ip6table_raw]
allowed = true
autoload = true

[settings.kernel.modules.ip6table_filter]
allowed = true
autoload = true
```

### PR DESCRIPTION
**Pull request by vigh-m**
**Issue number:**

Closes #3968 

**Description of changes:**
This change mounts the static kmod built in #3981 into a customer container. 

**Testing done:**
Tested on the host-ctr:
```
[ssm-user@control]$ enter-admin-container
Confirming admin container is enabled...
Waiting for admin container to start........
Entering admin container
          Welcome to Bottlerocket's admin container!
    ╱╲
   ╱┄┄╲   This container provides access to the Bottlerocket host
   │▗▖│   filesystems (see /.bottlerocket/rootfs) and contains common
  ╱│  │╲  tools for inspection and troubleshooting.  It is based on
  │╰╮╭╯│  Amazon Linux 2, and most things are in the same places you
    ╹╹    would find them on an AL2 host.

To permit more intrusive troubleshooting, including actions that mutate the
running state of the Bottlerocket host, we provide a tool called "sheltie"
(`sudo sheltie`).  When run, this tool drops you into a root shell in the
Bottlerocket host's root filesystem.
[root@admin]# ldd /usr/sbin/modprobe
  not a dynamic executable
```

Tested on a kubernetes container:
```
root@my-pod:/# ldd /usr/sbin/modprobe
  not a dynamic executable
root@my-pod:/# ldd /sbin/modprobe
  not a dynamic executable
root@my-pod:/# ldd /usr/bin/kmod
ldd: /usr/bin/kmod: No such file or directory
```

Pod Spec used:
```
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: ubuntu:noble
    command: ["/bin/sh", "-c", "while true; do echo 'Running...'; sleep 5; done"]
    securityContext:
      capabilities:
        add: ["SYS_MODULE"]
    volumeMounts:
    - name: kernel-modules
      mountPath: /lib/modules/
      readOnly: true
  volumes:
  - name: kernel-modules
    hostPath:
      path: /lib/modules/
```

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Comment by bcressey** [comment]
Code changes LGTM, though I would split them into one for host-ctr and one for containerd.

Does it work for Cilium? For the example pod spec, can you load a module via `modprobe`?

**Comment by yeazelm** [comment]
The code looks good, it would be awesome to include a before and after on that pod test to show the change, even better showing it loading a module after the fix to prove this fixes the issue.

**Comment by vigh-m** [comment]
Yeah. It loads the modules like expected. 
```
root@my-pod:/# ln -s /usr/sbin/modprobe /usr/bin/lsmod
root@my-pod:/# lsmod | grep tables
nf_tables             307200  0
nfnetlink              20480  2 nf_conntrack_netlink,nf_tables
root@my-pod:/# modprobe -r nf_tables
root@my-pod:/# lsmod | grep tables
root@my-pod:/# modprobe nf_tables
root@my-pod:/# lsmod | grep tables
nf_tables             307200  0
nfnetlink              20480  2 nf_conntrack_netlink,nf_tables
```

I had validated but didn't add it to the initial notes

**Comment by vigh-m** [comment]
Validated via SHA512 that it's the same modprobe

- On admin container
```
[root@admin]# sha512sum /usr/bin/kmod
b2f5451a89fc2e21a971b23086380ea3c8916b5ad753c31812b4419992e6f63687da3b35723ec1d1545039c4e946e54a01ff2555420966bcceda6bb8d0569404  /usr/bin/kmod
```
- On rootfs
```
[root@admin]# sha512sum /.bottlerocket/rootfs/bin/kmod
b2f5451a89fc2e21a971b23086380ea3c8916b5ad753c31812b4419992e6f63687da3b35723ec1d1545039c4e946e54a01ff2555420966bcceda6bb8d0569404  /.bottlerocket/rootfs/bin/kmod
```
- On container
```
root@my-pod:/# sha512sum /usr/sbin/modprobe
b2f5451a89fc2e21a971b23086380ea3c8916b5ad753c31812b4419992e6f63687da3b35723ec1d1545039c4e946e54a01ff2555420966bcceda6bb8d0569404  /usr/sbin/modprobe
```

**Review by yeazelm — APPROVED** [review]

**Comment by arnaldo2792** [comment]
For the validation, you could just have checked that the `modprobe` binary is coming from the host via `/proc/self/mountinfo`.

File: sources/host-ctr/cmd/host-ctr/main.go [hunk 1]
```diff
@@ -896,6 +896,12 @@ func withPrivilegedMounts() oci.SpecOpts {
 			Source:      "/mnt",
 			Type:        "bind",
 		},
+		{
+			Options:     []string{"rbind", "ro"},
```
Comment (arnaldo2792) [inline sources/host-ctr/cmd/host-ctr/main.go]: To be consistent with the other mount, this should be `bind` not `rbind`

File: packages/containerd/containerd-cri-base-json [hunk 2]
```diff
@@ -102,6 +102,15 @@ oci-defaults = { version = "v1", helpers = ["oci_defaults"] }
                 "mode=755",
                 "size=65536k"
             ]
+        },
+        {
+            "destination": "/sbin/modprobe",
```
Comment (arnaldo2792) [inline packages/containerd/containerd-cri-base-json:107]: One risk of this implementation is that if `PATH` is `/usr/bin:/sbin`, the `modprobe` binary in the container will be used instead of the injected `modprobe`. I guess that's a calculated risk to take, since we can't inject `modprobe` in every single path in `PATH`. Probably something to follow up for a later release is checking `PATH` and inject `modprobe` to the first path in that list.

**Review by bcressey — APPROVED** [review]
It would be good to validate that Cilium specifically works as expected with this change, in case there are more paths we need to bind to.

**Review by arnaldo2792 — APPROVED** [review]

**Comment by vigh-m** [comment]
New changes include:
- Updates to docker to inject kmod by default
- Fix based on comments
- Typo fixes

**Comment by vigh-m** [comment]
Fixing typo in the commit message

**Review by bcressey — APPROVED** [review]

**Review by yeazelm — APPROVED** [review]

**Comment by vigh-m** [comment]
Validated by running the `cilium/cilium:v1.15.5` image from DockerHub:

Locally launched container:
```
$ docker run -it --rm cilium/cilium:v1.15.5 sh
# ldd /usr/sbin/modprobe
	linux-vdso.so.1 (0x00007fffc838c000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f6632d16000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f6632ceb000)
	libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007f66328a7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f663267e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6632e14000)
# ls -la /usr/sbin/modprobe
lrwxrwxrwx. 1 root root 9 Aug 17  2021 /usr/sbin/modprobe -> /bin/kmod
# cat /proc/self/mountinfo  | grep kmod
#
```

VS container launched on bottlerocket
```
$ kubectl exec -it my-pod -- bash
root@my-pod:/home/cilium#
root@my-pod:/home/cilium# ldd /usr/sbin/modprobe
	not a dynamic executable
root@my-pod:/home/cilium# ls -la /usr/sbin/modprobe
lrwxrwxrwx. 1 root root 9 Aug 17  2021 /usr/sbin/modprobe -> /bin/kmod
root@my-pod:/home/cilium# ldd /bin/kmod
	not a dynamic executable
root@my-pod:/home/cilium# cat /proc/self/mountinfo | grep kmod
1281 1275 252:0 /x86_64-bottlerocket-linux-gnu/sys-root/usr/bin/kmod /usr/bin/kmod ro,relatime master:1 - ext4 /dev/root ro,seclabel,stripe=1024
```

I'm able to load and unload modules
```
root@my-pod:/home/cilium# lsmod | grep tables
nf_tables             307200  0
nfnetlink              20480  2 nf_conntrack_netlink,nf_tables
root@my-pod:/home/cilium# modprobe -r nf_tables
root@my-pod:/home/cilium# lsmod | grep tables
root@my-pod:/home/cilium# modprobe nf_tables
root@my-pod:/home/cilium# lsmod | grep tables
nf_tables             307200  0
nfnetlink              20480  2 nf_conntrack_netlink,nf_tables
```
