### PR TITLE
track and clean output files for builds

### LINKED ISSUE #1027: newer versions of RPMs will be used instead of the most recent builds
**Platform I'm building on:**
EC2

**What I expected to happen:**
After reverting a glibc package update, I expected that other package builds and the final image would use the older versions of glibc RPMs once they were rebuilt.

**What actually happened:**
Package builds and the final image used the newer versions of the glibc packages, since they were still present in `build/rpms` and available in the local repository that we generate.

**How to reproduce the problem:**
Bump the version in a spec file; build RPMs; revert the change; rebuild RPMs; check packages installed in `rpm2img` output.

### PR DESCRIPTION
**Pull request by bcressey**
**Issue number:**
Fixes #1027

**Description of changes:**
Add a layer of indirection between the build artifacts and the final output directory, so we can keep track of what we've previously built for a given package or variant.

That allows us to remove the files before the next build, so they do not interact with other builds in unexpected ways.

**Testing done:**
Verified that the `state` directory is populated with marker files.
```
❯ find build/state/variants -type f
build/state/variants/aws-k8s-1.17/bottlerocket-aws-k8s-1.17-aarch64-1.0.5-e3234419-data.img.lz4.marker
build/state/variants/aws-k8s-1.17/bottlerocket-aws-k8s-1.17-aarch64-1.0.5-e3234419-root.ext4.lz4.marker
build/state/variants/aws-k8s-1.17/bottlerocket-aws-k8s-1.17-aarch64-1.0.5-e3234419-migrations.tar.marker
build/state/variants/aws-k8s-1.17/bottlerocket-aws-k8s-1.17-aarch64-1.0.5-e3234419-boot.ext4.lz4.marker
build/state/variants/aws-k8s-1.17/bottlerocket-aws-k8s-1.17-aarch64-1.0.5-e3234419.img.lz4.marker
build/state/variants/aws-k8s-1.17/bottlerocket-aws-k8s-1.17-aarch64-1.0.5-e3234419-root.verity.lz4.marker
```

Confirmed that the corresponding files in `packages` and `images` are removed before another build. For example, old variant images are cleaned up on each build, so we no longer accumulate artifacts named for older commits. I also bumped the release package to version 1000.0, built it, then reverted it to 0.0. The older package with the higher version number was cleaned up as expected.

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

File: tools/buildsys/src/builder.rs [hunk 1]
```diff
@@ -161,7 +184,7 @@ fn build(target: &str, build_args: &str, tag: &str, output: &str) -> Result<()>
     ));
 
     let create = args(format!("create --name {tag} {tag} true", tag = tag));
-    let cp = args(format!("cp {}:/output/. {}", tag, output));
+    let cp = args(format!("cp {}:/output/. {}", tag, build_dir.display()));
```
Comment (webern) [inline tools/buildsys/src/builder.rs:187]: Would it be better to use rust instead of cp to do a copy here?

File: tools/buildsys/src/builder.rs [hunk 2]
```diff
@@ -255,6 +281,106 @@ where
...
 }
 
+/// Create a directory for build artifacts.
+fn create_build_dir(kind: &BuildType, name: &str) -> Result<PathBuf> {
+    let prefix = match kind {
+        BuildType::Package => "packages",
+        BuildType::Variant => "variants",
+    };
+
+    let path = [&getenv("BUILDSYS_STATE_DIR")?, prefix, name]
```
Comment (webern) [inline tools/buildsys/src/builder.rs:291]: At some point it might be nice to move all of these variables to a StructOpt, which can get its values from environment variables. This would make it easier to understand all of the inputs to the program by centralizing them.

**Review by webern — COMMENTED** [review]
So, because we rely on Cargo to detect changes, buildsys knows that it must rebuild, but sometimes it doesn't because rpmbuild sees the output files? Therefore you we now always delete those output RPM files? Do I understand correctly? Thanks.

File: tools/buildsys/src/builder.rs (hunk 1 above)
Comment (bcressey) [reply tools/buildsys/src/builder.rs:187]: This is a `docker cp` rather than a regular `cp`.

**Comment by bcressey** [comment]
> So, because we rely on Cargo to detect changes, buildsys knows that it must rebuild, but sometimes it doesn't because rpmbuild sees the output files? Therefore you we now always delete those output RPM files? Do I understand correctly? 

`buildsys` would always rebuild, but the output files from previous builds were not cleaned up, and accumulated in the `build/rpms` directory, and continued to be added to a repository for `dnf` to consume.

In the related issue, we observed that if we updated `glibc` to a newer version, then reverted that change because of a problem we found during testing, the newer versioned RPMs would still be there, and `dnf` would continue to install them instead of the most recently built RPMs, since package managers care about versions rather than timestamps.

Deleting the RPMs avoids the mismatch between what we expect the build system to do - packages and images should always use the most recently built dependencies - and what it actually does.

File: tools/buildsys/src/builder.rs (hunk 1 above)
Comment (webern) [reply tools/buildsys/src/builder.rs:187]: oh yeah

**Review by webern — APPROVED** [review]

File: tools/buildsys/src/builder/error.rs [hunk 3]
```diff
@@ -16,6 +16,36 @@ pub(crate) enum Error {
...
+
+    #[snafu(display("Failed to remove file '{}': {}", path.display(), source))]
+    FileRemove {
+        path: PathBuf,
+        source: std::io::Error,
+    },
+
+    #[snafu(display("Failed to rename file '{}': {}", path.display(), source))]
+    FileRename {
+        path: PathBuf,
```
Comment (tjkirch) [inline tools/buildsys/src/builder/error.rs]: The output path would be useful here too, in case it's a problem with the target directory.

File: tools/buildsys/src/builder.rs [hunk 4]
```diff
@@ -11,10 +11,13 @@ use duct::cmd;
 use nonzero_ext::nonzero;
 use rand::Rng;
 use sha2::{Digest, Sha512};
-use snafu::{ensure, ResultExt};
+use snafu::{ensure, OptionExt, ResultExt};
 use std::env;
+use std::fs;
```
Comment (tjkirch) [inline tools/buildsys/src/builder.rs]:
```suggestion
use std::fs::{File, self};
```

nit: `File` is usually used without the module prefix since it's so common.

File: tools/buildsys/src/builder.rs [hunk 5]
```diff
@@ -255,6 +281,106 @@ where
...
+/// Remove build artifacts from the output directory.
+fn clean_build_files<P>(build_dir: P, output_dir: P) -> Result<()>
+where
+    P: AsRef<Path>,
+{
+    fn is_marker(entry: &DirEntry) -> bool {
+        entry
+            .file_name()
+            .to_str()
+            .map(|s| s.ends_with(".marker"))
```
Comment (tjkirch) [inline tools/buildsys/src/builder.rs]:
```suggestion
            .map(|s| s.ends_with(".buildsys_marker"))
```
In case a package has a real `bla.marker` file...

On that note, it took me a while to understand what we're tracking here and the assumptions we're making.  I think we can only handle one level of files, no subdirectories, because we're not tracking anything about the path within the build / output directories.  I think it'd be worth documenting more of what's going on, example use cases, etc.

**Review by tjkirch — APPROVED** [review]
I don't want to block, but I do think documentation is important here.  The process makes some assumptions about the outputs of builds, and is something that could have subtle effects we're not anticipating.

Personally, I'm also worried about the removal of old artifacts, because of the impact to developer build time.  I don't think working on different branches should mean abandoning prior artifacts if relevant sources on the given branch haven't changed.  We _should_ be able to figure out use of the latest artifacts, but I know it's a hard problem, and we're solving something else here.

**Comment by bcressey** [comment]
> Personally, I'm also worried about the removal of old artifacts, because of the impact to developer build time. I don't think working on different branches should mean abandoning prior artifacts if relevant sources on the given branch haven't changed. We _should_ be able to figure out use of the latest artifacts, but I know it's a hard problem, and we're solving something else here.

Essentially this code only runs when `cargo` has already decided that a package needs to be rebuilt. That should always happen today when switching between branches where the files for a package have changed. If they haven't changed, then `cargo` should not see any modifications and won't start a rebuild.

If you're seeing spurious package rebuilds, it's possible we have another issue like the one in #996 that needs to be root caused.

File: tools/buildsys/src/builder.rs [hunk 6]
```diff
@@ -255,6 +281,114 @@ where
...
+    let path = [&getenv("BUILDSYS_STATE_DIR")?, prefix, name]
+        .iter()
+        .collect();
+
+    fs::create_dir_all(&path).context(error::DirectoryCreate { path: &path })?;
+
+    Ok(path)
+}
+
+static MARKER_EXTENSION: &str = ".buildsys_marker";
```
Comment (tjkirch) [inline tools/buildsys/src/builder.rs]:
```suggestion
const MARKER_EXTENSION: &str = ".buildsys_marker";
```

**Review by tjkirch — APPROVED** [review]

**Review by tjkirch — APPROVED** [review]
