### PR TITLE
testsys: Automatically create vSphere secret

### LINKED ISSUE #2658: `cargo make test`: TestSys not creating vsphere credential K8s secret when it should
**What I expected to happen:**
After exporting all the `GOVC_*` variables as described in https://github.com/bottlerocket-os/bottlerocket/blob/develop/TESTING.md#vmware-k8s, I expect `cargo make test` for vmware-k8s variant testing to work successfully without having to manually create the vsphere credentials in the TestSys cluster prior to running the tests.

**What actually happened:**

`cargo make test` creates the `vsphere-k8s-cluster-resource-agent` but it's missing vsphere credentials so the agent fails:

Checking logs:
```bash
bash-4.2$ kubectl --kubeconfig "${TESTSYS_KUBECONFIG}" logs -f x86-64-vmware-kef8e9be5-316d-4077-b68f-c42174a14397-creatibqnqk -n testsys                                                                                         
[2022-12-13T21:51:04Z INFO  resource_agent::agent] Initializing Agent
[2022-12-13T21:51:04Z ERROR resource_agent::agent] Resource action failed: Provider error: An error occurred but no resources were left behind, Unable to fetch vSphere credentials
[2022-12-13T21:51:04Z INFO  resource_agent::agent] 'keep_running' is true.
```
Checking resource object spec, notice how the `secret` is empty:
```bash
bash-4.2$ kubectl --kubeconfig "${TESTSYS_KUBECONFIG}" describe resources/x86-64-vmware-k8s -124 -n testsys
...
Spec:
  Agent:
    Capabilities:
    Configuration:
...
      Labels:
        testsys/arch:                  x86_64
        testsys/cluster:               x86-64-vmware-k8s-124
        testsys/controlPlaneEndpoint:  198.18.16.134
        testsys/type:                  cluster
        testsys/variant:               vmware-k8s-1.24
...
      Name:                            x86-64-vmware-k8s-124
      Ova Name:                        bottlerocket-vmware-k8s-1.24-x86_64-v1.12.0.ova
      Privileged:                      true
      Secrets:
...
      Vcenter Datacenter:       SDDC-Datacenter
      Vcenter Datastore:        WorkloadDatastore
      Vcenter Host URL:         ...
      Vcenter Network:          ...
      Vcenter Resource Pool:    ...
      Vcenter Workload Folder:  ...
      Version:                  v1.24
    Image:                      public.ecr.aws/bottlerocket-test-system/vsphere-k8s-cluster-resource-agent:v0.0.3
    Keep Running:               true
    Name:                       agent
    Privileged:                 true
    Pull Secret:                <nil>
    Secrets:
    Timeout:  <nil>
  Conflicts With:
  Depends On:
  Destruction Policy:  onTestSuccess

```

I also tried not exporting `GOVC_*` vars and just specifying the vmware datacenter config in `Infra.toml` and same thing happens.

**How to reproduce the problem:**

Either export `GOVC_*` or specify `vmware.datacenter` in `Infra.toml`.
Run
```bash
    cargo make \
      -e TESTSYS_TEST=migration \
      -e BUILDSYS_VARIANT="vmware-k8s-1.24" \
      -e BUILDSYS_ARCH="x86_64" \
      -e PUBLISH_INFRA_CONFIG_PATH="Infra.migration.toml" \
      -e TESTSYS_TEST_CONFIG_PATH="Test.toml" \
      test \
      --mgmt-cluster-kubeconfig="mgmt-cluster-eks-a-cluster.kubeconfig"
```

### PR DESCRIPTION
**Pull request by ecpullen**
<!--
Tips:
- Please read CONTRIBUTING.md to understand our process and our requests for PRs.
- Please file an issue before creating a PR so we can discuss the change and confirm it's not already being worked on.
-->

Note: This PR is dependent on TestSys v0.0.4

**Issue number:**

Closes #2658

**Description of changes:**

If a `vsphereCredential` secret is not in `Test.toml`, the secret will be automatically created.

**Testing done:**
Successfully kicked-off vsphere tests and saw that testsys created the vsphere creds automatically
```bash
$     cargo make       -e TESTSYS_KUBECONFIG=./mytestsys.kubeconfig       -e TESTSYS_TEST=quick       -e BUILDSYS_VARIANT=vmware-k8s-1.24       -e BUILDSYS_ARCH="x8                                                                                          
6_64"       -e TESTSYS_TEST_CONFIG_PATH="./Test.toml"       test       --mgmt-cluster-kubeconfig=mgmt-clust                                                                                      er-eks-a-cluster.kubeconfig                                                                                                                                                                                                                                   
[cargo-make] INFO - cargo make 0.35.12                                                                                                                                                                                                                        
[cargo-make] INFO - Build File: Makefile.toml                                                                                  
[cargo-make] INFO - Task: test                                                                                                 
[cargo-make] INFO - Profile: development                                                                                       
[cargo-make] INFO - Running Task: setup                                                                                                                                                                                                                       
[cargo-make] INFO - Running Task: fetch-sources                                                                                
[cargo-make] INFO - Running Task: test-tools                                                                                   
[cargo-make] INFO - Running Task: test                         
[2022-12-16T20:25:36Z INFO  testsys::run] Creating vSphere secret, 'vsphereCreds'                                              
[2022-12-16T20:25:36Z INFO  testsys::run] vSphere credentials file not found, will attempt to use environment                                                                                                                                                 
[2022-12-16T20:25:36Z INFO  testsys::run] Successfully added 'x86-64-vmware-k8s-124'                                                                                                                                                                          
[2022-12-16T20:25:37Z INFO  testsys::run] Successfully added 'x86-64-vmware-k8s-124-vms-quick'                                                                                                                                                                
[2022-12-16T20:25:37Z INFO  testsys::run] Successfully added 'x86-64-vmware-k8s-124-test'   
```
Verified that the vsphere resource agent was able to use said secret to talk to vsphere
```bash
$ cargo make -e TESTSYS_KUBECONFIG=./mytestsys.kubeconfig  testsys logs  --resource x86-64-vmware-k8s-124 --state=creation -f
[cargo-make] INFO - cargo make 0.35.12
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: testsys
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: setup
[cargo-make] INFO - Running Task: fetch-sources
[cargo-make] INFO - Running Task: test-tools
[cargo-make] INFO - Running Task: testsys
[2022-12-16T20:25:42Z INFO  resource_agent::agent] Initializing Agent
[2022-12-16T20:25:42Z INFO  vsphere_k8s_cluster_resource_agent::vsphere_k8s_cluster_provider] Getting vSphere secret
[2022-12-16T20:25:42Z INFO  vsphere_k8s_cluster_resource_agent::vsphere_k8s_cluster_provider] Creating working directory
[2022-12-16T20:25:42Z INFO  vsphere_k8s_cluster_resource_agent::vsphere_k8s_cluster_provider] Checking existing cluster
[2022-12-16T20:25:42Z INFO  vsphere_k8s_cluster_resource_agent::vsphere_k8s_cluster_provider] Creation policy is 'IfNotExists' and cluster 'x86-64-vmware-k8s-124' does not exist: creating cluster
[2022-12-16T20:25:42Z INFO  vsphere_k8s_cluster_resource_agent::vsphere_k8s_cluster_provider] Creating cluster
[2022-12-16T20:25:42Z INFO  vsphere_k8s_cluster_resource_agent::vsphere_k8s_cluster_provider] Downloading OVA 'bottlerocket-vmware-k8s-1.24-x86_64-v1.11.1.ova'
[2022-12-16T20:25:49Z INFO  vsphere_k8s_cluster_resource_agent::vsphere_k8s_cluster_provider] Importing OVA and creating a VM template out of it
[2022-12-16T20:26:02Z INFO  vsphere_k8s_cluster_resource_agent::vsphere_k8s_cluster_provider] Tagging VM template
...
```


**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by etungsten — COMMENTED** [review]
Thanks for the quick turnaround on this. LGTM if testing goes well. I can help with that if you'd like.

Can we please also update TESTING.md as part of this PR as well? It would be nice to add a reference to this section here under `vmware-k8s` testing regarding how to set up creds: https://github.com/bottlerocket-os/bottlerocket/blob/138d192daa90571503d1136f5c7934fdd12c925f/PUBLISHING-VMWARE.md?plain=1#L23-L35 

It does seem weird we'd have to add the cred config to a file under a hard-coded `~/.config/pubsys` directory for using it with testsys. But we can fix that later as a follow up.
https://github.com/bottlerocket-os/bottlerocket/blob/138d192daa90571503d1136f5c7934fdd12c925f/tools/pubsys-config/src/vmware.rs#L10-L18

File: tools/testsys/src/run.rs [hunk 1]
```diff
@@ -255,6 +258,48 @@ impl Run {
...
+                        })?;
+                    client
+                        .create_secret(
+                            &secret_name,
+                            vec![
+                                ("username".to_string(), creds.username),
+                                ("password".to_string(), creds.password),
+                            ],
+                        )
+                        .await?;
```
Comment (etungsten) [inline tools/testsys/src/run.rs:297]: What happens if the secret already exists? Can we make sure it replaces it if it already exists? (upsert)

**Review by webern — APPROVED** [review]

File: tools/testsys/src/run.rs (hunk 1 above)
Comment (ecpullen) [reply tools/testsys/src/run.rs:297]: It should be ok. I will verify it when testing.

**Review by etungsten — APPROVED** [review]
