### PR TITLE
During kubelet prestart, skip pause image pull if image exist

### LINKED ISSUE #2567: Cannot restart Kubelet when there is no network connection
**Image I'm using:**
bottlerocket-aws-k8s-1.21-x86_64-v1.8.0-a6233c22

**What I expected to happen:**
When I reboot my machine when there is no network connection, I am expecting `kubelet` to come back online or to at least see the process failing to start. If there is no network connection, I should see the `kubelet` running on the cached container. 

**What actually happened:**
The container in which the `kubelet` is executed is not able to start because BR [instructs containerd](https://github.com/bottlerocket-os/bottlerocket/blob/e8a5391ac70829ad8c259671676a0e131ddd6673/sources/host-ctr/cmd/host-ctr/main.go#L983-L991) to call ECR to fetch the image rather than use the cached version.

```
Nov 08 20:18:19 ip-10-0-3-98.us-west-2.compute.internal host-ctr[1102632]: time="2022-11-08T20:18:19Z" level=info msg="pulling with Amazon ECR Resolver" ref="ecr.aws/arn:aws:ecr:us-west-2:193646904820:repository/eks/eks-distro/kubernetes/pause:v1.21.14-eks-1-21-19"
Nov 08 20:19:49 ip-10-0-3-98.us-west-2.compute.internal systemd[1]: kubelet.service: start-pre operation timed out. Terminating.
Nov 08 20:19:49 ip-10-0-3-98.us-west-2.compute.internal systemd[1]: kubelet.service: Control process exited, code=killed, status=15/TERM
Nov 08 20:19:49 ip-10-0-3-98.us-west-2.compute.internal systemd[1]: kubelet.service: Failed with result 'timeout'.
Nov 08 20:19:49 ip-10-0-3-98.us-west-2.compute.internal systemd[1]: Failed to start Kubelet.
```

**How to reproduce the problem:**
1. Create a CPI or worker node with BR in AWS.
2. Start SSM Session
3. Remove network access to machine by removing all egress security group traffic. SSM session should continue to work at this point.
4. Restart `kubelet`
5. `kubelet` is never initalized.

### PR DESCRIPTION
**Pull request by etungsten**
**Issue number:**
Resolves https://github.com/bottlerocket-os/bottlerocket/issues/2567

**Description of changes:**
```
    kubernetes: during kubelet prestart, skip pause image pull if exist
    
    This makes it so that if the pause container image already exists in
    containerd's image store, host-ctr won't try to authenticate and pull
    the pause image and let kubelet use the cached image copy.
```
```
    host-ctr: add flag for skipping image pull if cached copy exists
    
    This adds a new flag to both `run` and `pull-image` subcommands to skip
    image pull and the associated registry authentications if a local cached
    copy of the image exists.
```

**Testing done:**
Testing locally:
Pull image when it doesn't exist locally
```bash
$ sudo ./host-ctr --containerd-socket=/run/containerd/containerd.sock --namespace=k8s.io pull-image --source=public.ecr.aws/eks-distro/kubernetes/pause:3.5 --skip-if-image-exist=true                                                                                                                                                                             
time="2022-11-16T15:52:29-08:00" level=info msg="Image does not exist, proceeding to pull image from source." ref="public.ecr.aws/eks-distro/kubernetes/pause:3.5"                                 
time="2022-11-16T15:52:35-08:00" level=warning msg="ecr-public: failed to get authorization token, falling back to default resolver (unauthenticated pull)"                                        
time="2022-11-16T15:52:36-08:00" level=info msg="pulled image successfully" img="public.ecr.aws/eks-distro/kubernetes/pause:3.5"                                                                   
time="2022-11-16T15:52:36-08:00" level=info msg="unpacking image..." img="public.ecr.aws/eks-distro/kubernetes/pause:3.5"                                                                          
```
After, pulling the same image with `--skip-if-image-exist=true`
```bash                                                                                                                  
$ sudo ./host-ctr --containerd-socket=/run/containerd/containerd.sock --namespace=k8s.io pull-image --source=public.ecr.aws/eks-distro/kubernetes/pause:3.5 --skip-if-image-exist=true             
time="2022-11-16T15:52:37-08:00" level=info msg="Image exists, fetching cached image from image store" ref="public.ecr.aws/eks-distro/kubernetes/pause:3.5"                                  
```

Testing on aws-k8s-1.22 built from this branch:
Launched with `settings.kubernetes.standalone-mode=true`, kubelet is running fine initally:
```bash
[root@admin]# sudo sheltie                                                                                                                                                                           bash-5.1# systemctl status kubelet                                                                                                                                                                   
● kubelet.service - Kubelet                                                                                                                                                                          
     Loaded: loaded (/aarch64-bottlerocket-linux-gnu/sys-root/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)                                                               
    Drop-In: /etc/systemd/system/kubelet.service.d                                                                                                                                                   
             └─exec-start.conf                                                                                                                                                                       
             /aarch64-bottlerocket-linux-gnu/sys-root/usr/lib/systemd/system/kubelet.service.d                                                                                                       
             └─load-ipvs-modules.conf, make-kubelet-dirs.conf, prestart-pull-pause-ctr.conf                                                                                                                  
Active: active (running) since Thu 2022-11-17 00:12:48 UTC; 1min 56s ago                                                                                               
...
```
Then I removed network egress from the instance's security group. Restarted kubelet and it comes up fine:
```bash
bash-5.1# systemctl status kubelet               
● kubelet.service - Kubelet                      
     Loaded: loaded (/aarch64-bottlerocket-linux-gnu/sys-root/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)                                                               
    Drop-In: /etc/systemd/system/kubelet.service.d                                                
             └─exec-start.conf                   
             /aarch64-bottlerocket-linux-gnu/sys-root/usr/lib/systemd/system/kubelet.service.d    
             └─load-ipvs-modules.conf, make-kubelet-dirs.conf, prestart-pull-pause-ctr.conf       
     Active: active (running) since Thu 2022-11-17 00:17:50 UTC; 3s ago                                                                                                                              
...
```
Then I manually tried pulling the pause container image and it skips the image pull as expected.
```bash
bash-5.1# /usr/bin/host-ctr \                    
>     --containerd-socket=/run/dockershim.sock \                                                  
>     --namespace=k8s.io \                       
>     pull-image \                               
>     --source=602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pause:3.1-eksbuild.1 \            
>     --registry-config=/etc/host-containers/host-ctr.toml \                                      
>     --skip-if-image-exist=true                 
time="2022-11-17T00:18:40Z" level=info msg="Image exists, fetching cached image from image store" ref="ecr.aws/arn:aws:ecr:us-west-2:602401143452:repository/eks/pause:3.1-eksbuild.1"               
time="2022-11-17T00:18:40Z" level=info msg="tagging image" img="602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pause:3.1-eksbuild.1" 
```

Testing `host-ctr run --use-cached-image` and it works as expected. If the image is already there, start the host-container task without pulling the image again:
```
bash-5.1# /usr/bin/host-ctr run --container-id=admin2 --source=328549459982.dkr.ecr.us-west-2.amazonaws.com/bottlerocket-admin:v0.9.3 --use-cached-image=true
time="2022-11-17T00:41:24Z" level=info msg="Image exists, fetching cached image from image store" ref="ecr.aws/arn:aws:ecr:us-west-2:328549459982:repository/bottlerocket-admin:v0.9.3"
time="2022-11-17T00:41:24Z" level=info msg="tagging image" img="328549459982.dkr.ecr.us-west-2.amazonaws.com/bottlerocket-admin:v0.9.3"
time="2022-11-17T00:41:24Z" level=info msg="Container does not exist, proceeding to create it" ctr-id=admin2
time="2022-11-17T00:41:24Z" level=info msg="container task does not exist, proceeding to create it" container-id=admin2
...
```

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by stmcginnis — APPROVED** [review]
Looks good! Thanks for the great detail on testing in the PR description.

File: sources/host-ctr/cmd/host-ctr/main.go [hunk 1]
```diff
@@ -882,6 +894,25 @@ func withProxyEnv() oci.SpecOpts {
...
+// fetchImage returns a `containerd.Image` given an image source.
+func fetchImage(ctx context.Context, source string, client *containerd.Client, registryConfigPath string, fetchCachedImageIfExist bool) (containerd.Image, error) {
+	// Check the containerd image store to see if image exists
+	img, err := client.GetImage(ctx, source)
+	if err != nil {
+		if errdefs.IsNotFound(err) {
+			log.G(ctx).WithField("ref", source).Info("Image does not exist, proceeding to pull image from source.")
+		} else {
+			log.G(ctx).WithField("ref", source).Error(err)
+			return nil, err
```
Comment (webern) [inline sources/host-ctr/cmd/host-ctr/main.go:906]: I wonder if there are cases where this is not a fatal error? Unlikely I guess.

**Review by webern — APPROVED** [review]
nice

File: sources/host-ctr/cmd/host-ctr/main.go (hunk 1 above)
Comment (jpmcb) [reply sources/host-ctr/cmd/host-ctr/main.go:906]: [Doesn't look like it](https://github.com/containerd/containerd/blob/722df11e920cf23563eccef7e2edbcc1f729de29/errdefs/errors.go#L51-L92).

Seems the only time we care to not continue and attempt to pull the image is if it can't be found.

**Review by jpmcb — APPROVED** [review]
👏🏼 👏🏼 👏🏼

File: sources/host-ctr/cmd/host-ctr/main.go [hunk 2]
```diff
@@ -148,9 +155,15 @@ func App() *cli.App {
 					Usage:       "path to image registry configuration",
 					Destination: &registryConfig,
 				},
+				&cli.BoolFlag{
+					Name:        "skip-if-image-exist",
```
Comment (bcressey) [inline sources/host-ctr/cmd/host-ctr/main.go]: nit: maybe "skip-if-image-exists"

File: sources/host-ctr/cmd/host-ctr/main.go [hunk 3]
```diff
@@ -495,16 +508,15 @@ func pullImageOnly(containerdSocket string, namespace string, source string, reg
 
 	// Parse the source ref if it looks like an ECR ref.
 	isECRImage := ecrRegex.MatchString(source)
-	ref := source
```
Comment (bcressey) [inline sources/host-ctr/cmd/host-ctr/main.go:498]: Why make this change?

File: sources/host-ctr/cmd/host-ctr/main.go [hunk 4]
```diff
@@ -882,6 +894,25 @@ func withProxyEnv() oci.SpecOpts {
 	return oci.Compose(withHttpsProxy, withNoProxy)
 }
 
+// fetchImage returns a `containerd.Image` given an image source.
+func fetchImage(ctx context.Context, source string, client *containerd.Client, registryConfigPath string, fetchCachedImageIfExist bool) (containerd.Image, error) {
```
Comment (bcressey) [inline sources/host-ctr/cmd/host-ctr/main.go]: nit: it might be better to reuse the `useCachedImage` parameter name everywhere.

it could be a bit confusing to see that `skipIfExist = true` (implying that any action would be skipped) and then see "Image exists, fetching cached image from image store" get logged (implying that something was fetched).

File: sources/host-ctr/cmd/host-ctr/main.go (hunk 3 above)
Comment (jpmcb) [reply sources/host-ctr/cmd/host-ctr/main.go:498]: This change makes sense to me: `ref` is a copy of the `source` string which is redundant. Instead, the change to just use `source` seems more simple without introducing an additional variable.

Comment (etungsten) [reply sources/host-ctr/cmd/host-ctr/main.go:498]: Yeah, this is a vestige of some preprocessing I did with the ECR image source to convert it to a ECR resolver compatible image reference. Now it's redundant to make a copy of the variable.

Comment (etungsten) [reply sources/host-ctr/cmd/host-ctr/main.go:498]: Lemme capture this in a separate commit, the comment there is also inaccurate now

**Comment by etungsten** [comment]
Pushes above addresses @bcressey 's comments:

- Change option name "skip-if-image-exist" -> "skip-if-image-exists"
- Rename parameter name to be more clear
- Move clean-up changes to a separate commit

Repeated testing and the results are the same as described in the PR description.

**Comment by etungsten** [comment]
Woops, i mixed up one of the commits. fixing

**Comment by etungsten** [comment]
Push above has no changes, just moves changes to their appropriate commits.

**Review by bcressey — APPROVED** [review]
