### PR TITLE
pubsys: improve messages for publish-ami command

### LINKED ISSUE #2688: pubsys: improve logging for publish-ami
**What I'd like:**

During `pubsys publish-ami`, which is called by `cargo make ami-public`, certain error paths can be confusing. It can appear that an error occurred for one region only, and that the other regions were successfully made public when, in fact, no regions were made public.

This contributed to bottlerocket-os/bottlerocket#2617. We are taking other, stronger measures to ensure that private AMIs cannot be promoted to public SSM params (these include, but are not limited to, bottlerocket-os/twoliter#493 and bottlerocket-os/bottlerocket#2680). In addition to such stronger measures, we also want to improve error messaging.

The confusing error looked like this:

```
Failed to publish AMI: AMI 'ami-xyz123' in some-region-1 did not become available: Failed to reach desired state within 90 attempts for ami-xyz123 in some-region-1
```

It came from here:

https://github.com/bottlerocket-os/bottlerocket/blob/develop/tools/pubsys/src/aws/publish_ami/mod.rs#L173..L178

It could lead someone to believe that only one region (i.e. `some-region-1`) has failed to become public. In fact what it means is that one of the AMIs was detected to be unavailable, and the operation was aborted before ANY AMIs were made public.

The goal of this issue is to make this error condition more clear.
At the same time, we may want to reduce the verbosity of the "happy" path to draw more attention to error conditions.

### PR DESCRIPTION
**Pull request by webern**
Reduce verbosity and clarify error conditions in publish-ami.

## Issue number:

Closes #2688

## Description of changes:

For the `publish-ami` command:
- Slightly reduce logging verbosity
- Clarify some log messages
- Clarify error conditions that lead to zero AMIs being published

### Before these Changes

**Error Path**

```
20:23:13 [INFO] Using AMI data from path: /home/x/repos/bottlerocket/build/images/x86_64-aws-k8s-1.23/1.12.0-aeb95d83/bottlerocket-aws-k8s-1.23-x86_64-1.12.0-aeb95d83-amis.json
20:23:13 [INFO] Waiting for AMIs to be available...
20:23:13 [INFO] Waiting for ami-04e85be49d294275c in us-west-2 to be available... (attempt 1 of 90)
20:23:19 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 1 of 90)
20:23:21 [INFO] provider returned CredentialsNotLoaded, ignoring
20:23:21 [INFO] Waiting for ami-0c6efd0a3cf83b6c0 in us-west-1 to be available... (attempt 1 of 90)
20:23:23 [INFO] Waiting for ami-04a38d08dfee9430e in ap-northeast-1 to be available... (attempt 1 of 90)
20:23:25 [INFO] Found ami-05489572a30afaae3 available in af-south-1
20:23:25 [INFO] provider returned CredentialsNotLoaded, ignoring
20:23:31 [INFO] provider returned CredentialsNotLoaded, ignoring
20:23:36 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 6 of 90)
20:23:48 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 11 of 90)
20:23:59 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 16 of 90)
20:24:11 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 21 of 90)
20:24:22 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 26 of 90)
20:24:34 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 31 of 90)
20:24:46 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 36 of 90)
20:24:57 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 41 of 90)
20:25:09 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 46 of 90)
20:25:20 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 51 of 90)
20:25:32 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 56 of 90)
20:25:43 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 61 of 90)
20:25:55 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 66 of 90)
20:26:06 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 71 of 90)
20:26:18 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 76 of 90)
20:26:29 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 81 of 90)
20:26:41 [INFO] Waiting for ami-0fb30279737b04eb5 in us-east-1 to be available... (attempt 86 of 90)
Failed to publish AMI: AMI 'ami-04e85be49d294275c' in us-west-2 did not become available: Failed to describe images in us-west-2: failed to construct request: No credentials in the property bag
```

**Happy Path**

```
20:35:01 [INFO] Using AMI data from path: /home/x/repos/bottlerocket/build/images/x86_64-aws-k8s-1.23/1.12.0-aeb95d83/bottlerocket-aws-k8s-1.23-x86_64-1.12.0-aeb95d83-amis.json
20:35:01 [INFO] Waiting for AMIs to be available...
20:35:02 [INFO] Found ami-04e85be49d294275c available in us-west-2
20:35:02 [INFO] Found ami-0c6efd0a3cf83b6c0 available in us-west-1
20:35:02 [INFO] Found ami-0fb30279737b04eb5 available in us-east-1
20:35:02 [INFO] Found ami-04a38d08dfee9430e available in ap-northeast-1
20:35:03 [INFO] Found ami-05489572a30afaae3 available in af-south-1
20:35:04 [INFO] Updating snapshot permissions - granting access
20:35:05 [INFO] Updating image permissions - granting access
20:35:05 [INFO] Modified permissions of image ami-0c6efd0a3cf83b6c0 in us-west-1
20:35:05 [INFO] Modified permissions of image ami-0fb30279737b04eb5 in us-east-1
20:35:05 [INFO] Modified permissions of image ami-04a38d08dfee9430e in ap-northeast-1
20:35:05 [INFO] Modified permissions of image ami-05489572a30afaae3 in af-south-1
20:35:05 [INFO] Modified permissions of image ami-04e85be49d294275c in us-west-2
```

### After these Changes

**Error Path**

```
20:19:07 [INFO] Using AMI data from path: /home/x/repos/bottlerocket/build/images/x86_64-aws-k8s-1.23/1.12.0-11f46927/bottlerocket-aws-k8s-1.23-x86_64-1.12.0-11f46927-amis.json
20:19:07 [INFO] Waiting for all 5 AMIs to be available before changing any of their permissions
20:19:07 [INFO] Waiting for ami-077e452dff44ef3ca in us-west-2 to be available... (attempt 1 of 90)
20:19:09 [INFO] Waiting for ami-0b029c3d70ad88c0a in us-west-1 to be available... (attempt 1 of 90)
20:19:11 [INFO] provider returned CredentialsNotLoaded, ignoring
20:19:11 [INFO] Waiting for ami-0896fc4409dc0b916 in us-east-1 to be available... (attempt 1 of 90)
20:19:15 [INFO] provider returned CredentialsNotLoaded, ignoring
20:19:17 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 1 of 90)
20:19:19 [INFO] provider returned CredentialsNotLoaded, ignoring
20:19:20 [INFO] Found ami-03e1123698e77270d available in af-south-1
20:19:30 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 6 of 90)
20:19:42 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 11 of 90)
20:19:54 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 16 of 90)
20:20:06 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 21 of 90)
20:20:19 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 26 of 90)
20:20:31 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 31 of 90)
20:20:43 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 36 of 90)
20:20:55 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 41 of 90)
20:21:07 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 46 of 90)
20:21:20 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 51 of 90)
20:21:32 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 56 of 90)
20:21:44 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 61 of 90)
20:21:56 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 66 of 90)
20:22:08 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 71 of 90)
20:22:21 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 76 of 90)
20:22:33 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 81 of 90)
20:22:45 [INFO] Waiting for ami-0d9a51431f7c2cdf0 in ap-northeast-1 to be available... (attempt 86 of 90)
Error during publish-ami command: No AMI permissions were updated: AMI 'ami-077e452dff44ef3ca' in us-west-2 did not become available: Failed to describe images in us-west-2: failed to construct request: No credentials in the property bag
```

**Happy Path**

```
20:24:32 [INFO] Using AMI data from path: /home/x/repos/bottlerocket/build/images/x86_64-aws-k8s-1.23/1.12.0-11f46927/bottlerocket-aws-k8s-1.23-x86_64-1.12.0-11f46927-amis.json
20:24:32 [INFO] Waiting for all 5 AMIs to be available before changing any of their permissions
20:24:32 [INFO] Found ami-077e452dff44ef3ca available in us-west-2
20:24:32 [INFO] Found ami-0b029c3d70ad88c0a available in us-west-1
20:24:32 [INFO] Found ami-0896fc4409dc0b916 available in us-east-1
20:24:32 [INFO] Found ami-0d9a51431f7c2cdf0 available in ap-northeast-1
20:24:33 [INFO] Found ami-03e1123698e77270d available in af-south-1
20:24:34 [INFO] Updating all snapshot permissions before changing any AMI permissions - granting access
20:24:35 [INFO] Updating AMI permissions - granting access
20:24:36 [INFO] Modified permissions of image ami-077e452dff44ef3ca in us-west-2
20:24:36 [INFO] Modified permissions of image ami-0b029c3d70ad88c0a in us-west-1
20:24:36 [INFO] Modified permissions of image ami-0d9a51431f7c2cdf0 in ap-northeast-1
20:24:36 [INFO] Modified permissions of image ami-03e1123698e77270d in af-south-1
20:24:36 [INFO] Modified permissions of image ami-0896fc4409dc0b916 in us-east-1
```

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

File: tools/pubsys/src/main.rs [hunk 1]
```diff
@@ -182,7 +182,7 @@ mod error {
         #[snafu(display("Logger setup error: {}", source))]
         Logger { source: log::SetLoggerError },
 
-        #[snafu(display("Failed to publish AMI: {}", source))]
+        #[snafu(display("Error during publish-ami command: {}", source))]
```
Comment (stmcginnis) [inline tools/pubsys/src/main.rs]: nit: I would actually keep this one as it was. We call this using the `publish-ami` command, but pubsys can be called on its own, so the original statement was more accurate and doesn't change any meaning.

**Review by stmcginnis — APPROVED** [review]
This looks much better!

In the new failure example published, we should probably fail right away instead of retrying repeatedly with an error condition like that. But that can be another update. At least with this change it is much more clear what is happening.

File: tools/pubsys/src/main.rs (hunk 1 above)
Comment (webern) [reply tools/pubsys/src/main.rs]: I think the original statement was problematic because `"Failed to publish AMI: {}"` made it sound like a single AMI failed. How about `"Failure during AMI publication: {}"`?

File: tools/pubsys/src/aws/ami/wait.rs [hunk 2]
```diff
@@ -59,7 +59,7 @@ pub(crate) async fn wait_for_ami(
                             saw_it = true;
                             successes += 1;
                             if successes >= successes_required {
-                                info!("Found {} {} in {}", id, state, region);
+                                debug!("Found {} {} in {}", id, state, region);
```
Comment (etungsten) [inline tools/pubsys/src/aws/ami/wait.rs]: I think I prefer seeing the AMI-ID in at least one of the `info` level logs in the happy path. With this change, the happy path doesn't seem to show what the AMI-IDs of the images being operated on are.

File: tools/pubsys/src/main.rs (hunk 1 above)
Comment (webern) [reply tools/pubsys/src/main.rs]: > nit: I would actually keep this one as it was. We call this using the `publish-ami` command, but pubsys can be called on its own, so the original statement was more accurate and doesn't change any meaning.

Actually, I'm not sure what you mean by "pubsys can be called on its own". This error variant is only used in one place, which is during the `publish-ami` command. And this is a main.rs file so there's no way for it to be used somewhere else. Can you clarify the use-case where you think this error message would be incorrect?

File: tools/pubsys/src/aws/publish_ami/mod.rs [hunk 3]
```diff
@@ -574,7 +584,7 @@ mod error {
         },
 
         #[snafu(display(
-            "Failed to modify permissions of {} of {} snapshots",
+            "No AMIs were made public because we failed to modify permissions of {} of {} snapshots",
             error_count, error_count + success_count,
         ))]
         ModifySnapshotAttributes {
```
Comment (etungsten) [inline tools/pubsys/src/aws/publish_ami/mod.rs]: Non-blocking comment/nit:

I understand we need to tell users that no AMIs were made public when this error occurs, but can we do it by wrapping the original error message so that `ModifySnapshotAttributes` stands on its own and can be used for errors that occur outside of the context of making AMIs public? So the resulting error message would be something like:
>No AMIs were made public: Failed to modify permissions of {} of {} snapshots

Same comment for `WaitAmi` in the context of publishing a single AMI amongst many.

File: tools/pubsys/src/aws/ami/wait.rs [hunk 4]
```diff
@@ -91,7 +91,8 @@ pub(crate) async fn wait_for_ami(
             successes = 0;
         };
 
-        if attempts % 5 == 1 {
+        // Let the user know we are still trying without being too verbose.
+        if attempts % 10 == 0 && attempts > max_attempts / 2 {
```
Comment (etungsten) [inline tools/pubsys/src/aws/ami/wait.rs]: nit: Maybe it's my personal preference but I like seeing things being outputted to know for sure something is happening and not just hanging. In the PR description error path example, there was nothing outputted for 2 minutes.

```suggestion
        if attempts % 10 == 0 {
```

Comment (yeazelm) [reply tools/pubsys/src/aws/ami/wait.rs]: I agree that we should provide some feedback to the user, any time a tool "hangs" without explaining that it is actually doing something is a bad user experience. Ideally we would emit the first time we plan to wait just so the user knows they are entering a waiting period vs "doing things" period in the tool.

File: tools/pubsys/src/aws/publish_ami/mod.rs [hunk 5]
```diff
@@ -156,7 +156,14 @@ pub(crate) async fn run(args: &Args, publish_args: &PublishArgs) -> Result<()> {
...
     // If AMIs aren't in "available" state, we can get a DescribeImages response that includes
     // most of the data we need, but not snapshot IDs.
-    info!("Waiting for AMIs to be available...");
+    if amis.len() == 1 {
+        info!("Waiting for AMI to be available before making it public")
+    } else {
+        info!(
+            "Waiting for all {} AMIs to be available before making any of them public",
+            amis.len(),
+        );
```
Comment (yeazelm) [inline tools/pubsys/src/aws/publish_ami/mod.rs]: I like this a lot!

File: tools/pubsys/src/aws/ami/wait.rs (hunk 2 above)
Comment (webern) [reply tools/pubsys/src/aws/ami/wait.rs]: @yeazelm: yeah or nay from you on this change from `info!` to `debug!`? One of the issue we were trying to deal with is the verbosity of the happy path when hundreds of AMIs are being handled.

**Comment by webern** [comment]
^ Rebase https://github.com/bottlerocket-os/bottlerocket/compare/0f4c4b05ec3c76b7934e0ca49aabb6bb3fcd06e6..0113236f35b544397d80f315ae54e19831fa5fd1

File: tools/pubsys/src/aws/publish_ami/mod.rs (hunk 3 above)
Comment (webern) [reply tools/pubsys/src/aws/publish_ami/mod.rs]: That's not easy to do because `ModifyImagesAttributes` is a case where some of the AMIs are published and some aren't. I see your point though, because these functions are `pub(crate)` and used by the `ami` command.

I will need to find a way to fix this.

File: tools/pubsys/src/aws/ami/wait.rs (hunk 2 above)
Comment (yeazelm) [reply tools/pubsys/src/aws/ami/wait.rs]: I think emitting the AMI ID to the user is good as a default. Its a lot, but it is probably the one string they might be looking for while its running (to confirm they are operating on the AMIs the expect).

**Comment by webern** [comment]
^ undo unpopular changes and make some of the messages more generic since they could occur either when amis are being made public or when permissions are being revoked. https://github.com/bottlerocket-os/bottlerocket/compare/0113236f35b544397d80f315ae54e19831fa5fd1..245eb694562cc69074c6b4039a52a69319b68bcc

File: tools/pubsys/src/aws/ami/wait.rs (hunk 2 above)
Comment (webern) [reply tools/pubsys/src/aws/ami/wait.rs]: I reverted this change in https://github.com/bottlerocket-os/bottlerocket/compare/0113236f35b544397d80f315ae54e19831fa5fd1..245eb694562cc69074c6b4039a52a69319b68bcc

File: tools/pubsys/src/aws/ami/wait.rs (hunk 4 above)
Comment (webern) [reply tools/pubsys/src/aws/ami/wait.rs]: I reverted this change in https://github.com/bottlerocket-os/bottlerocket/compare/0113236f35b544397d80f315ae54e19831fa5fd1..245eb694562cc69074c6b4039a52a69319b68bcc

**Comment by webern** [comment]
^ relegate the interpretation of the error, and it's affect on AMI publication, to the higher level error message. However there is some kind of weird git regression in this one and another push is required: https://github.com/bottlerocket-os/bottlerocket/compare/245eb694562cc69074c6b4039a52a69319b68bcc..5d55fc994ea41754fc895e9ba8d12371422ace0c

**Comment by webern** [comment]
^ Fix the weird git regression https://github.com/bottlerocket-os/bottlerocket/compare/5d55fc994ea41754fc895e9ba8d12371422ace0c..5e4df513eebaa8fcd70d482a8514b5677eaea237

**Review by etungsten — APPROVED** [review]

**Comment by webern** [comment]
^ I got clippied https://github.com/bottlerocket-os/bottlerocket/compare/5e4df513eebaa8fcd70d482a8514b5677eaea237..11f46927afb08671e83abe5657555db52a543c5b

**Review by etungsten — APPROVED** [review]

**Comment by webern** [comment]
Updated the PR description with new output

**Review by yeazelm — APPROVED** [review]

**Review by zmrow — APPROVED** [review]
:zap:

File: tools/pubsys/src/main.rs (hunk 1 above)
Comment (stmcginnis) [reply tools/pubsys/src/main.rs]: Sorry, I was just thinking of `cargo make publish-ami`. We're good now.

**Review by stmcginnis — APPROVED** [review]
