### PR TITLE
fix clippy warnings for sources

### LINKED ISSUE #1776: build: check clippy and cargo fmt during github actions checks
**What I'd like:**

During GitHub actions CI, the build should fail (preferably early) if the code is not fmt'ed with cargo fmt and if it has cargo clippy warnings.

We probably wouldn't want this to happen as part of the RPM build process. Instead this would probably be more like what we do now with `cargo test`. The downside is that a mismatch between the version of cargo in the build runners and a developer's local version of cargo could cause a mismatch in clippy lints (less likely that a fmt mismatch would occur).

**Any alternatives you've considered:**

- Doing this with the SDK
- Doing this with "local" cargo/rust
- Don't check lint/fmt in CI

### PR DESCRIPTION
**Pull request by bcressey**
**Issue number:**

Fixes #1776 (finally)

**Description of changes:**
Fix all clippy warnings for the `sources` tree, and add coverage to the CI lint checks.

**Testing done:**
`cargo make check-lints` passes for three platforms:
* `aws-k8s-1.24`
* `vmware-k8s-1.24`
* `metal-k8s-1.24`

**Terms of contribution:**

By submitting this pull request, I agree that this contribution is dual-licensed under the terms of both the Apache License, version 2.0, and the MIT license.

### CODE REVIEW

**Review by stmcginnis — APPROVED** [review]
A lot of files touched, but overall not too bad considering no linting was being performed before.

I tried looking through for any nuanced behavioral changes, but nothing stood out. Looks good to me.

File: sources/updater/update_metadata/src/lib.rs [hunk 1]
```diff
@@ -369,23 +366,21 @@ impl Update {
...
-                    }
-                    let time_per_seed = wave_duration / num_seeds_allocated_to_wave;
-                    // Derive the target time position within the wave given the host's seed.
-                    let target_time = start_time + (time_per_seed * (seed as i32));
-                    // If the current time is past the target time position in the wave, the update is
-                    // marked available
-                    return time >= target_time;
+            if let Some((start_time, Some(end_time), start_seed, end_seed)) = bound {
+                // This host is not part of last wave
+                // Determine the duration of this host's wave
```
Comment (etungsten) [inline sources/updater/update_metadata/src/lib.rs:371]: I think this might be a case of the previous being better for readability? But this is also fine.

File: sources/cfsignal/src/cloudformation.rs [hunk 2]
```diff
@@ -33,7 +33,7 @@ pub async fn signal_resource(
         .logical_resource_id(logical_resource_id)
         .status(
             aws_sdk_cloudformation::model::ResourceSignalStatus::from_str(&status)
-                .context(error::ParseStatusSnafu)?,
+                .expect("infallible"),
```
Comment (webern) [inline sources/cfsignal/src/cloudformation.rs:36]: I don't like it, but OK. I should read up on infallible errors.

**Review by zmrow — APPROVED** [review]
Thanks!

:gem:

**Review by etungsten — APPROVED** [review]

File: sources/api/migration/migration-helpers/src/common_migrations.rs [hunk 3]
```diff
@@ -703,6 +700,7 @@ impl Migration for ReplaceTemplateMigration {
             self.update_template_and_data(
                 // Clone the input string; we need to give the function mutable access to
                 // the structure that contains the string, so we can't pass a reference into the structure.
+                #[allow(clippy::unnecessary_to_owned)]
                 &data.to_owned(),
```
Comment (webern) [inline sources/api/migration/migration-helpers/src/common_migrations.rs:704]: This doesn't work?

```suggestion
                &data,
```

**Review by webern — APPROVED** [review]
Nice, we probably want to merge this asap.

File: sources/api/thar-be-updates/src/status.rs [hunk 4]
```diff
@@ -100,11 +100,9 @@ pub fn get_update_status(_lockfile: &File) -> Result<UpdateStatus> {
...
         path: UPDATE_STATUS_FILE,
     })?;
-    Ok(
-        serde_json::from_reader(status_file).context(error::StatusParseSnafu {
-            path: UPDATE_STATUS_FILE,
-        })?,
-    )
+    serde_json::from_reader(status_file).context(error::StatusParseSnafu {
+        path: UPDATE_STATUS_FILE,
+    })
```
Comment (yeazelm) [inline sources/api/thar-be-updates/src/status.rs:105]: How is the `Result` returned without the `Ok()`?

**Review by yeazelm — APPROVED** [review]
LGTM but I will admit I'm unsure of the `Box`ing of those errors.

File: sources/api/thar-be-updates/src/status.rs (hunk 4 above)
Comment (webern) [reply sources/api/thar-be-updates/src/status.rs:105]: `.context` converts the `Result<JsonError` to `Result<OurError>` which is being returned since we are not using `?` on it.

Comment (yeazelm) [reply sources/api/thar-be-updates/src/status.rs:105]: Thanks!

File: sources/cfsignal/src/cloudformation.rs (hunk 2 above)
Comment (bcressey) [reply sources/cfsignal/src/cloudformation.rs:36]: This avoids a clippy warning about unreachable code in the error type, behind the `Snafu` proc macro. I couldn't find a way to retain the `ParseStatus` enum variant and get rid of the warning.

File: sources/api/migration/migration-helpers/src/common_migrations.rs (hunk 3 above)
Comment (bcressey) [reply sources/api/migration/migration-helpers/src/common_migrations.rs:704]: That's what clippy suggests, but it leads to this compiler error:
```
error[E0502]: cannot borrow `input` as mutable because it is also borrowed as immutable
   --> api/migration/migration-helpers/src/common_migrations.rs:706:17
    |
690 |         if let Some(input_value) = input.data.get(self.setting) {
    |                                    ---------------------------- immutable borrow occurs here
...
700 |             self.update_template_and_data(
    |                  ------------------------ immutable borrow later used by call
...
706 |                 &mut input,
    |                 ^^^^^^^^^^ mutable borrow occurs here
```

File: sources/api/migration/migrations/v1.12.0/add-k8s-autoscaling-warm-pool-setting-metadata/src/main.rs [hunk 5]
```diff
@@ -10,7 +10,7 @@ fn run() -> Result<()> {
         migrate(AddMetadataMigration(&[SettingMetadata {
             metadata: &["affected-services"],
             setting: "settings.autoscaling",
-        }]));
+        }]))?;
     };
```
Comment (cbgbt) [inline sources/api/migration/migrations/v1.12.0/add-k8s-autoscaling-warm-pool-setting-metadata/src/main.rs:14]: I hadn't considered that stuff like this isn't currently caught by CI. Awesome.

File: sources/api/datastore/src/key.rs [hunk 6]
```diff
@@ -232,10 +232,7 @@ impl Key {
     /// Determines whether a character is acceptable within a segment of a key name.  This is
     /// separate from quoting; if a character isn't valid, it isn't valid quoted, either.
     fn valid_character(c: char) -> bool {
-        match c {
-            'a'..='z' | 'A'..='Z' | '0'..='9' | '_' | '-' | '/' => true,
-            _ => false,
-        }
+        matches!(c, 'a'..='z' | 'A'..='Z' | '0'..='9' | '_' | '-' | '/')
```
Comment (cbgbt) [inline sources/api/datastore/src/key.rs:235]: TIL about `matches!`

**Review by cbgbt — APPROVED** [review]
Nice! 🚀

File: sources/api/datastore/src/key.rs (hunk 6 above)
Comment (bcressey) [reply sources/api/datastore/src/key.rs:235]: Me too!
